global:
  scrape_interval: 5s
  scrape_timeout: 4s
  external_labels:
    monitor: ticket-app

scrape_configs:
  - job_name: ticket-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app-1:8080", "app-2:8080"]

  - job_name: prometheus
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: mysql
    static_configs:
      - targets: ["mysqld-exporter:9104"]

  - job_name: redis
    static_configs:
      - targets: ["redis-exporter:9121"]
